### ISSUE TITLE
kelp init fails

### ISSUE THREAD

**Issue by untcha** [crhuber/kelp#13]
Hi 👋🏻 
yesterday I tried to install kelp, but it fails with the following message:

```
./kelp init
2024/01/26 09:25:11 unexpected end of JSON input
```

I'm using an M1 MacBook Pro and used `kelp_1.12.2_darwin_arm64`

**Comment by crhuber** [comment]
Fixed in https://github.com/crhuber/kelp/releases/tag/v1.12.3

**Comment by crhuber** [comment]
Try the latest release 1.12.4

**Comment by untcha** [comment]
Works fine! 👍🏻 
Thanks a lot!
